version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /data
  delete:
    enabled: true
http:
  addr: 127.0.0.1:10042
  debug:
    addr: 127.0.0.1:10043
    prometheus:
      enabled: true
      path: "/metrics"
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
compatibility:
  schema1:
    enabled: false
